/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ca.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../../public/stylesheets/ca.component.css.shim';
import * as import11 from 'ng2-smooth-scroll/lib/ng2-SmoothScroll.directive';
var renderType_CAComponent_Host:import0.RenderComponentType = (null as any);
class _View_CAComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CAComponent_0_4:import3.CAComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CAComponent_Host0,renderType_CAComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-ca',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CAComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CAComponent_0_4 = new import3.CAComponent();
    this._appEl_0.initComponent(this._CAComponent_0_4,[],compView_0);
    compView_0.create(this._CAComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CAComponent) && (0 === requestNodeIndex))) { return this._CAComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._CAComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_CAComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CAComponent_Host === (null as any))) { (renderType_CAComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_CAComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CAComponentNgFactory:import9.ComponentFactory<import3.CAComponent> = new import9.ComponentFactory<import3.CAComponent>('page-ca',viewFactory_CAComponent_Host0,import3.CAComponent);
const styles_CAComponent:any[] = [import10.styles];
var renderType_CAComponent:import0.RenderComponentType = (null as any);
class _View_CAComponent0 extends import1.AppView<import3.CAComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _text_132:any;
  _el_133:any;
  _text_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _text_141:any;
  _text_142:any;
  _text_143:any;
  _el_144:any;
  _text_145:any;
  _el_146:any;
  _text_147:any;
  _el_148:any;
  _SmoothScrollToDirective_148_3:import11.SmoothScrollToDirective;
  _text_149:any;
  _text_150:any;
  _el_151:any;
  _SmoothScrollToDirective_151_3:import11.SmoothScrollToDirective;
  _text_152:any;
  _text_153:any;
  _el_154:any;
  _SmoothScrollToDirective_154_3:import11.SmoothScrollToDirective;
  _text_155:any;
  _text_156:any;
  _el_157:any;
  _SmoothScrollToDirective_157_3:import11.SmoothScrollToDirective;
  _text_158:any;
  _text_159:any;
  _text_160:any;
  _text_161:any;
  _el_162:any;
  _text_163:any;
  _el_164:any;
  _text_165:any;
  _el_166:any;
  _el_167:any;
  _text_168:any;
  _text_169:any;
  _el_170:any;
  _el_171:any;
  _text_172:any;
  _text_173:any;
  _el_174:any;
  _text_175:any;
  _el_176:any;
  _el_177:any;
  _text_178:any;
  _text_179:any;
  _text_180:any;
  _text_181:any;
  _text_182:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CAComponent0,renderType_CAComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','customBody');
    this.renderer.setElementAttribute(this._el_0,'style','background-color:white;');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container');
    this._text_3 = this.renderer.createText(this._el_2,'\n        \n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this.renderer.setElementAttribute(this._el_4,'id','myheading');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-md-8 col-md-offset-2');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'a',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','home');
    this._text_9 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_6,'img',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','logoImage');
    this.renderer.setElementAttribute(this._el_10,'src','../../../public/images/logo.png');
    this.renderer.setElementAttribute(this._el_10,'style','margin-bottom: -35px; filter:brightness(0);');
    this._text_11 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','row');
    this.renderer.setElementAttribute(this._el_12,'style','margin-bottom: 70px; margin-top: 30px;');
    this._text_13 = this.renderer.createText(this._el_12,' \n                    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'p',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','myheading1');
    this._text_15 = this.renderer.createText(this._el_14,'MECHANICA | IIT MADRAS',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'id','mydiv1');
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'p',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','myheading2');
    this._text_21 = this.renderer.createText(this._el_20,'CAMPUS AMBASSADOR',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'p',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','mybottomline');
    this._text_24 = this.renderer.createText(this._el_23,'BECOME THE STAR OF YOUR COLLEGE',(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_26 = this.renderer.createText(this._el_6,'\n                \n                ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','col-md-3 buttonPosi');
    this.renderer.setElementAttribute(this._el_27,'style','margin-top: 100px;');
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'a',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','myButton');
    this.renderer.setElementAttribute(this._el_29,'href','https://mechanica.typeform.com/to/MHR1fQ');
    this._text_30 = this.renderer.createText(this._el_29,'Register',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','row');
    this.renderer.setElementAttribute(this._el_35,'id','myabout');
    this._text_36 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','col-md-8 col-md-offset-2');
    this._text_38 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'p',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','mynormalheading');
    this._text_40 = this.renderer.createText(this._el_39,'ABOUT',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'p',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','mydata');
    this._text_43 = this.renderer.createText(this._el_42,'\n                    Mechanica is the technical festival of Mechanical Engineering,\n                    presented by Mechanical Engineering Association (MEA),\n                    the largest of its kind at IIT Madras. \n                    The fest was started as a humble attempt to strengthen the foundations of mechanical students,\n                    and, pave a way for them to understand theory in the context of real life,\n                    with a glistening variety of contests and events. \n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_46 = this.renderer.createText(this._el_2,'\n        \n        ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','row');
    this.renderer.setElementAttribute(this._el_47,'id','myca');
    this._text_48 = this.renderer.createText(this._el_47,'\n            ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_47,'div',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','col-md-8 col-md-offset-2');
    this._text_50 = this.renderer.createText(this._el_49,'\n                    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'p',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','mynormalheading');
    this._text_52 = this.renderer.createText(this._el_51,'Why Become a CA',(null as any));
    this._text_53 = this.renderer.createText(this._el_49,'\n                    ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_49,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','mydata');
    this._text_55 = this.renderer.createText(this._el_54,'\n                        The Campus Ambassador Program is a platform for you to improve your communication, \n                        marketing and social skills. \n                        It offers a whole range of activities which give you a hands-on \n                        experience in digital marketing, publicity and event management.\n                        ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'span',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','incentives');
    this._text_57 = this.renderer.createText(this._el_56,' The incentives include:\n                        \n                            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','row');
    this.renderer.setElementAttribute(this._el_58,'style','text-align:center; margin-top: 20px;');
    this._text_59 = this.renderer.createText(this._el_58,'\n                            \n                                ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','col-md-4');
    this._text_61 = this.renderer.createText(this._el_60,'\n                                    ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'img',(null as any));
    this.renderer.setElementAttribute(this._el_62,'src','../../../public/images/internship.jpg');
    this.renderer.setElementAttribute(this._el_62,'width','100px');
    this._text_63 = this.renderer.createText(this._el_60,'\n                                    ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_60,'h4',(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'Internship & Passport',(null as any));
    this._text_66 = this.renderer.createText(this._el_60,'\n                                    \n                                        ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_60,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_67,'style','list-style: none; padding-left: 0px;');
    this._text_68 = this.renderer.createText(this._el_67,'\n                                            ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_67,'li',(null as any));
    this.renderer.setElementAttribute(this._el_69,'style','margin-bottom: 5px;');
    this._text_70 = this.renderer.createText(this._el_69,'Top 5 CAs willget free accommodation during Mechanica.',(null as any));
    this._text_71 = this.renderer.createText(this._el_67,'\n                                            ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_67,'li',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Top 3 CAs stand a chance to win cash prizes worth Rs 3000/-',(null as any));
    this._text_74 = this.renderer.createText(this._el_67,'\n                                        ',(null as any));
    this._text_75 = this.renderer.createText(this._el_60,'\n                                    \n                                ',(null as any));
    this._text_76 = this.renderer.createText(this._el_58,'\n\n                                ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_58,'div',(null as any));
    this.renderer.setElementAttribute(this._el_77,'class','col-md-4');
    this._text_78 = this.renderer.createText(this._el_77,'\n                                    ',(null as any));
    this._el_79 = this.renderer.createElement(this._el_77,'img',(null as any));
    this.renderer.setElementAttribute(this._el_79,'src','../../../public/images/certificate.jpg');
    this.renderer.setElementAttribute(this._el_79,'width','100px');
    this._text_80 = this.renderer.createText(this._el_77,'\n                                    ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_77,'h4',(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Certificate of Appreciation',(null as any));
    this._text_83 = this.renderer.createText(this._el_77,'\n\n                                    ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_77,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_84,'style','list-style: none; padding-left: 0px;');
    this._text_85 = this.renderer.createText(this._el_84,'\n                                            ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_84,'li',(null as any));
    this.renderer.setElementAttribute(this._el_86,'style','margin-bottom: 5px;');
    this._text_87 = this.renderer.createText(this._el_86,'Best CA will be awarded a special certificate of appreciation from HOD.',(null as any));
    this._text_88 = this.renderer.createText(this._el_84,'\n                                    ',(null as any));
    this._text_89 = this.renderer.createText(this._el_77,'\n\n                                ',(null as any));
    this._text_90 = this.renderer.createText(this._el_58,'\n\n                                ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_58,'div',(null as any));
    this.renderer.setElementAttribute(this._el_91,'class','col-md-4');
    this._text_92 = this.renderer.createText(this._el_91,'\n                                    ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_91,'img',(null as any));
    this.renderer.setElementAttribute(this._el_93,'src','../../../public/images/rewarded.jpg');
    this.renderer.setElementAttribute(this._el_93,'width','100px');
    this._text_94 = this.renderer.createText(this._el_91,'\n                                    ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_91,'h4',(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'Improve Your Skills',(null as any));
    this._text_97 = this.renderer.createText(this._el_91,'\n                                    ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_91,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_98,'style','list-style: none; padding-left: 0px;');
    this._text_99 = this.renderer.createText(this._el_98,'\n                                            ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_98,'li',(null as any));
    this.renderer.setElementAttribute(this._el_100,'style','margin-bottom: 5px;');
    this._text_101 = this.renderer.createText(this._el_100,'The ability to motivate and lead a team.',(null as any));
    this._text_102 = this.renderer.createText(this._el_98,'\n                                            ',(null as any));
    this._el_103 = this.renderer.createElement(this._el_98,'li',(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'Excellent Communication and \'People Skills\'.',(null as any));
    this._text_105 = this.renderer.createText(this._el_98,'\n                                    ',(null as any));
    this._text_106 = this.renderer.createText(this._el_91,'\n                                ',(null as any));
    this._text_107 = this.renderer.createText(this._el_58,'\n\n                            ',(null as any));
    this._text_108 = this.renderer.createText(this._el_56,'\n                        ',(null as any));
    this._text_109 = this.renderer.createText(this._el_54,'\n                    ',(null as any));
    this._text_110 = this.renderer.createText(this._el_49,'\n            ',(null as any));
    this._text_111 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._text_112 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_113,'class','row');
    this.renderer.setElementAttribute(this._el_113,'id','myrespon');
    this._text_114 = this.renderer.createText(this._el_113,'\n            ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_113,'div',(null as any));
    this.renderer.setElementAttribute(this._el_115,'class','col-md-8 col-md-offset-2');
    this._text_116 = this.renderer.createText(this._el_115,'\n                ',(null as any));
    this._el_117 = this.renderer.createElement(this._el_115,'p',(null as any));
    this.renderer.setElementAttribute(this._el_117,'class','mynormalheading');
    this._text_118 = this.renderer.createText(this._el_117,'RESPONSIBILITIES',(null as any));
    this._text_119 = this.renderer.createText(this._el_115,'\n                ',(null as any));
    this._el_120 = this.renderer.createElement(this._el_115,'div',(null as any));
    this.renderer.setElementAttribute(this._el_120,'class','mydata');
    this._text_121 = this.renderer.createText(this._el_120,'\n                    ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_120,'ul',(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_122,'li',(null as any));
    this.renderer.setElementAttribute(this._el_124,'style','margin-bottom: 10px;');
    this._text_125 = this.renderer.createText(this._el_124,'Creating Brand Awareness about MECHANICA 2018 in and around the campus.',(null as any));
    this._text_126 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_127 = this.renderer.createElement(this._el_122,'li',(null as any));
    this.renderer.setElementAttribute(this._el_127,'style','margin-bottom: 10px;');
    this._text_128 = this.renderer.createText(this._el_127,'Introduce and execute on ground publicity of Mechanica by posters in your campus.',(null as any));
    this._text_129 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_130 = this.renderer.createElement(this._el_122,'li',(null as any));
    this.renderer.setElementAttribute(this._el_130,'style','margin-bottom: 10px;');
    this._text_131 = this.renderer.createText(this._el_130,'Facilitate two ways communication between Mechanica and your Institution.',(null as any));
    this._text_132 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_133 = this.renderer.createElement(this._el_122,'li',(null as any));
    this.renderer.setElementAttribute(this._el_133,'style','margin-bottom: 10px;');
    this._text_134 = this.renderer.createText(this._el_133,'Ensure student participation from his/her college  during MECHANICA 2018 at IIT MADRAS.',(null as any));
    this._text_135 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_122,'li',(null as any));
    this.renderer.setElementAttribute(this._el_136,'style','margin-bottom: 10px;');
    this._text_137 = this.renderer.createText(this._el_136,'Share Facebook and Whatsapp posts.',(null as any));
    this._text_138 = this.renderer.createText(this._el_122,'\n                    ',(null as any));
    this._text_139 = this.renderer.createText(this._el_120,'\n                ',(null as any));
    this._text_140 = this.renderer.createText(this._el_115,'\n            ',(null as any));
    this._text_141 = this.renderer.createText(this._el_113,'\n        ',(null as any));
    this._text_142 = this.renderer.createText(this._el_2,'  \n        \n',(null as any));
    this._text_143 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_144 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_144,'id','mynavbar');
    this._text_145 = this.renderer.createText(this._el_144,'\n            ',(null as any));
    this._el_146 = this.renderer.createElement(this._el_144,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_146,'style','list-style-type: none;');
    this._text_147 = this.renderer.createText(this._el_146,'\n                ',(null as any));
    this._el_148 = this.renderer.createElement(this._el_146,'li',(null as any));
    this.renderer.setElementAttribute(this._el_148,'class','navbtn');
    this.renderer.setElementAttribute(this._el_148,'duration','1800');
    this.renderer.setElementAttribute(this._el_148,'offset','100');
    this.renderer.setElementAttribute(this._el_148,'scrollTo','myheading');
    this._SmoothScrollToDirective_148_3 = new import11.SmoothScrollToDirective();
    this._text_149 = this.renderer.createText(this._el_148,'Home',(null as any));
    this._text_150 = this.renderer.createText(this._el_146,'\n                ',(null as any));
    this._el_151 = this.renderer.createElement(this._el_146,'li',(null as any));
    this.renderer.setElementAttribute(this._el_151,'class','navbtn');
    this.renderer.setElementAttribute(this._el_151,'duration','1800');
    this.renderer.setElementAttribute(this._el_151,'offset','100');
    this.renderer.setElementAttribute(this._el_151,'scrollTo','myabout');
    this._SmoothScrollToDirective_151_3 = new import11.SmoothScrollToDirective();
    this._text_152 = this.renderer.createText(this._el_151,'About',(null as any));
    this._text_153 = this.renderer.createText(this._el_146,'\n                ',(null as any));
    this._el_154 = this.renderer.createElement(this._el_146,'li',(null as any));
    this.renderer.setElementAttribute(this._el_154,'class','navbtn');
    this.renderer.setElementAttribute(this._el_154,'duration','1800');
    this.renderer.setElementAttribute(this._el_154,'offset','100');
    this.renderer.setElementAttribute(this._el_154,'scrollTo','myca');
    this._SmoothScrollToDirective_154_3 = new import11.SmoothScrollToDirective();
    this._text_155 = this.renderer.createText(this._el_154,'Why CA',(null as any));
    this._text_156 = this.renderer.createText(this._el_146,'\n                ',(null as any));
    this._el_157 = this.renderer.createElement(this._el_146,'li',(null as any));
    this.renderer.setElementAttribute(this._el_157,'class','navbtn');
    this.renderer.setElementAttribute(this._el_157,'duration','1800');
    this.renderer.setElementAttribute(this._el_157,'offset','100');
    this.renderer.setElementAttribute(this._el_157,'scrollTo','myrespon');
    this._SmoothScrollToDirective_157_3 = new import11.SmoothScrollToDirective();
    this._text_158 = this.renderer.createText(this._el_157,'Responsibilites',(null as any));
    this._text_159 = this.renderer.createText(this._el_146,'\n            ',(null as any));
    this._text_160 = this.renderer.createText(this._el_144,'\n        ',(null as any));
    this._text_161 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_162 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_162,'id','myfooter');
    this._text_163 = this.renderer.createText(this._el_162,'\n\n            ',(null as any));
    this._el_164 = this.renderer.createElement(this._el_162,'a',(null as any));
    this.renderer.setElementAttribute(this._el_164,'href','https://www.iitm.ac.in/');
    this._text_165 = this.renderer.createText(this._el_164,'\n               ',(null as any));
    this._el_166 = this.renderer.createElement(this._el_164,'i',(null as any));
    this.renderer.setElementAttribute(this._el_166,'style','font-size: 36px; margin-right:20px;');
    this._el_167 = this.renderer.createElement(this._el_166,'img',(null as any));
    this.renderer.setElementAttribute(this._el_167,'height','45px');
    this.renderer.setElementAttribute(this._el_167,'src','../../../public/images/iitmlogo.png');
    this._text_168 = this.renderer.createText(this._el_164,'\n            ',(null as any));
    this._text_169 = this.renderer.createText(this._el_162,'\n\n            ',(null as any));
    this._el_170 = this.renderer.createElement(this._el_162,'a',(null as any));
    this.renderer.setElementAttribute(this._el_170,'href','https://www.facebook.com/mechanica.iitm');
    this.renderer.setElementAttribute(this._el_170,'target','_blank');
    this._el_171 = this.renderer.createElement(this._el_170,'i',(null as any));
    this.renderer.setElementAttribute(this._el_171,'class','fa fa-facebook-square');
    this.renderer.setElementAttribute(this._el_171,'style','font-size: 36px;');
    this._text_172 = this.renderer.createText(this._el_170,'\n            ',(null as any));
    this._text_173 = this.renderer.createText(this._el_162,'\n\n            ',(null as any));
    this._el_174 = this.renderer.createElement(this._el_162,'a',(null as any));
    this.renderer.setElementAttribute(this._el_174,'href','https://www.facebook.com/iitmmea/');
    this._text_175 = this.renderer.createText(this._el_174,'\n               ',(null as any));
    this._el_176 = this.renderer.createElement(this._el_174,'i',(null as any));
    this.renderer.setElementAttribute(this._el_176,'style','font-size: 36px;');
    this._el_177 = this.renderer.createElement(this._el_176,'img',(null as any));
    this.renderer.setElementAttribute(this._el_177,'height','45px');
    this.renderer.setElementAttribute(this._el_177,'src','../../../public/images/mea.png');
    this._text_178 = this.renderer.createText(this._el_174,'\n            ',(null as any));
    this._text_179 = this.renderer.createText(this._el_162,'\n            ',(null as any));
    this._text_180 = this.renderer.createText(this._el_162,'\n        ',(null as any));
    this._text_181 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_182 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_148,'click',this.eventHandler(this._handle_click_148_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_151,'click',this.eventHandler(this._handle_click_151_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_154,'click',this.eventHandler(this._handle_click_154_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_157,'click',this.eventHandler(this._handle_click_157_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._text_141,
      this._text_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._text_150,
      this._el_151,
      this._text_152,
      this._text_153,
      this._el_154,
      this._text_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._text_159,
      this._text_160,
      this._text_161,
      this._el_162,
      this._text_163,
      this._el_164,
      this._text_165,
      this._el_166,
      this._el_167,
      this._text_168,
      this._text_169,
      this._el_170,
      this._el_171,
      this._text_172,
      this._text_173,
      this._el_174,
      this._text_175,
      this._el_176,
      this._el_177,
      this._text_178,
      this._text_179,
      this._text_180,
      this._text_181,
      this._text_182
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.SmoothScrollToDirective) && ((148 <= requestNodeIndex) && (requestNodeIndex <= 149)))) { return this._SmoothScrollToDirective_148_3; }
    if (((token === import11.SmoothScrollToDirective) && ((151 <= requestNodeIndex) && (requestNodeIndex <= 152)))) { return this._SmoothScrollToDirective_151_3; }
    if (((token === import11.SmoothScrollToDirective) && ((154 <= requestNodeIndex) && (requestNodeIndex <= 155)))) { return this._SmoothScrollToDirective_154_3; }
    if (((token === import11.SmoothScrollToDirective) && ((157 <= requestNodeIndex) && (requestNodeIndex <= 158)))) { return this._SmoothScrollToDirective_157_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'myheading';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._SmoothScrollToDirective_148_3.scrollTo = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '1800';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._SmoothScrollToDirective_148_3.duration = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = '100';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._SmoothScrollToDirective_148_3.offset = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'myabout';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._SmoothScrollToDirective_151_3.scrollTo = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = '1800';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._SmoothScrollToDirective_151_3.duration = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = '100';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._SmoothScrollToDirective_151_3.offset = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = 'myca';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._SmoothScrollToDirective_154_3.scrollTo = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = '1800';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._SmoothScrollToDirective_154_3.duration = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = '100';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._SmoothScrollToDirective_154_3.offset = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = 'myrespon';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._SmoothScrollToDirective_157_3.scrollTo = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = '1800';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._SmoothScrollToDirective_157_3.duration = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = '100';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._SmoothScrollToDirective_157_3.offset = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_148_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SmoothScrollToDirective_148_3.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_151_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SmoothScrollToDirective_151_3.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_154_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SmoothScrollToDirective_154_3.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_157_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SmoothScrollToDirective_157_3.onClick()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CAComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CAComponent> {
  if ((renderType_CAComponent === (null as any))) { (renderType_CAComponent = viewUtils.createRenderComponentType('C:/Users/Shiv Tavker/Documents/Mechanica Final/assets/app/CAPortal/ca.component.html',0,import8.ViewEncapsulation.Emulated,styles_CAComponent,{})); }
  return new _View_CAComponent0(viewUtils,parentInjector,declarationEl);
}