/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.container[_ngcontent-%COMP%]{\r\n    \r\n\r\n    text-align: center;\r\n    color: white;\r\n    font-family: Arial;\r\n    font-style: italic;\r\n}\r\n            \r\n.container[_ngcontent-%COMP%]   header[_ngcontent-%COMP%]{\r\n    font-size: 40px;\r\n    margin-top: 50px;\r\n    margin-bottom: 20px;\r\n}\r\n\r\n.container[_ngcontent-%COMP%]   section[_ngcontent-%COMP%]{\r\n    margin-top: 50px;\r\n    text-align: left;\r\n}\r\n            \r\n.container[_ngcontent-%COMP%]   section[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\r\n    color: black;\r\n}'];