/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/core/src/application_init';
import * as import8 from '@angular/core/src/testability/testability';
import * as import9 from '@angular/core/src/application_ref';
import * as import10 from '@angular/core/src/linker/compiler';
import * as import11 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import12 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import13 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import14 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import15 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import16 from '@angular/core/src/linker/view_utils';
import * as import17 from '@angular/platform-browser/src/browser/title';
import * as import18 from '@angular/common/src/location/location';
import * as import19 from '@angular/router/src/url_tree';
import * as import20 from '@angular/router/src/router_outlet_map';
import * as import21 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import22 from '@angular/core/src/di/injector';
import * as import23 from './Home/home.component.ngfactory';
import * as import24 from './CAPortal/ca.component.ngfactory';
import * as import25 from './Inaugration/inaugration.component.ngfactory';
import * as import26 from './app.component.ngfactory';
import * as import27 from '@angular/core/src/application_tokens';
import * as import28 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import29 from '@angular/platform-browser/src/dom/events/key_events';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import32 from '@angular/common/src/location/platform_location';
import * as import33 from '@angular/common/src/location/location_strategy';
import * as import34 from './Home/home.component';
import * as import35 from './CAPortal/ca.component';
import * as import36 from './Inaugration/inaugration.component';
import * as import37 from '@angular/router/src/router';
import * as import38 from '@angular/core/src/console';
import * as import39 from '@angular/core/src/i18n/tokens';
import * as import40 from '@angular/core/src/error_handler';
import * as import41 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import42 from '@angular/platform-browser/src/dom/animation_driver';
import * as import43 from '@angular/core/src/render/api';
import * as import44 from '@angular/core/src/security';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import46 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import47 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import48 from '@angular/router/src/router_config_loader';
import * as import49 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _AppModule_5:import1.AppModule;
  __LOCALE_ID_6:any;
  __NgLocalization_7:import6.NgLocaleLocalization;
  _ErrorHandler_8:any;
  _ApplicationInitStatus_9:import7.ApplicationInitStatus;
  _Testability_10:import8.Testability;
  _ApplicationRef__11:import9.ApplicationRef_;
  __ApplicationRef_12:any;
  __Compiler_13:import10.Compiler;
  __APP_ID_14:any;
  __DOCUMENT_15:any;
  __HAMMER_GESTURE_CONFIG_16:import11.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_17:any[];
  __EventManager_18:import12.EventManager;
  __DomSharedStylesHost_19:import13.DomSharedStylesHost;
  __AnimationDriver_20:any;
  __DomRootRenderer_21:import14.DomRootRenderer_;
  __RootRenderer_22:any;
  __DomSanitizer_23:import15.DomSanitizerImpl;
  __Sanitizer_24:any;
  __ViewUtils_25:import16.ViewUtils;
  __IterableDiffers_26:any;
  __KeyValueDiffers_27:any;
  __SharedStylesHost_28:any;
  __Title_29:import17.Title;
  __ROUTER_CONFIGURATION_30:any;
  __LocationStrategy_31:any;
  __Location_32:import18.Location;
  __UrlSerializer_33:import19.DefaultUrlSerializer;
  __RouterOutletMap_34:import20.RouterOutletMap;
  __NgModuleFactoryLoader_35:import21.SystemJsNgModuleLoader;
  __ROUTES_36:any[];
  __Router_37:any;
  __ActivatedRoute_38:any;
  __APP_BOOTSTRAP_LISTENER_39:any[];
  constructor(parent:import22.Injector) {
    super(parent,[
      import23.HomeComponentNgFactory,
      import24.CAComponentNgFactory,
      import25.InaugrationComponentNgFactory,
      import23.HomeComponentNgFactory,
      import26.AppComponentNgFactory
    ]
    ,[import26.AppComponentNgFactory]);
  }
  get _LOCALE_ID_6():any {
    if ((this.__LOCALE_ID_6 == (null as any))) { (this.__LOCALE_ID_6 = 'en-US'); }
    return this.__LOCALE_ID_6;
  }
  get _NgLocalization_7():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == (null as any))) { (this.__NgLocalization_7 = new import6.NgLocaleLocalization(this._LOCALE_ID_6)); }
    return this.__NgLocalization_7;
  }
  get _ApplicationRef_12():any {
    if ((this.__ApplicationRef_12 == (null as any))) { (this.__ApplicationRef_12 = this._ApplicationRef__11); }
    return this.__ApplicationRef_12;
  }
  get _Compiler_13():import10.Compiler {
    if ((this.__Compiler_13 == (null as any))) { (this.__Compiler_13 = new import10.Compiler()); }
    return this.__Compiler_13;
  }
  get _APP_ID_14():any {
    if ((this.__APP_ID_14 == (null as any))) { (this.__APP_ID_14 = import27._appIdRandomProviderFactory()); }
    return this.__APP_ID_14;
  }
  get _DOCUMENT_15():any {
    if ((this.__DOCUMENT_15 == (null as any))) { (this.__DOCUMENT_15 = import4._document()); }
    return this.__DOCUMENT_15;
  }
  get _HAMMER_GESTURE_CONFIG_16():import11.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_16 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_16 = new import11.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_16;
  }
  get _EVENT_MANAGER_PLUGINS_17():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_17 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_17 = [
      new import28.DomEventsPlugin(),
      new import29.KeyEventsPlugin(),
      new import11.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_16)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_17;
  }
  get _EventManager_18():import12.EventManager {
    if ((this.__EventManager_18 == (null as any))) { (this.__EventManager_18 = new import12.EventManager(this._EVENT_MANAGER_PLUGINS_17,this.parent.get(import30.NgZone))); }
    return this.__EventManager_18;
  }
  get _DomSharedStylesHost_19():import13.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_19 == (null as any))) { (this.__DomSharedStylesHost_19 = new import13.DomSharedStylesHost(this._DOCUMENT_15)); }
    return this.__DomSharedStylesHost_19;
  }
  get _AnimationDriver_20():any {
    if ((this.__AnimationDriver_20 == (null as any))) { (this.__AnimationDriver_20 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_20;
  }
  get _DomRootRenderer_21():import14.DomRootRenderer_ {
    if ((this.__DomRootRenderer_21 == (null as any))) { (this.__DomRootRenderer_21 = new import14.DomRootRenderer_(this._DOCUMENT_15,this._EventManager_18,this._DomSharedStylesHost_19,this._AnimationDriver_20)); }
    return this.__DomRootRenderer_21;
  }
  get _RootRenderer_22():any {
    if ((this.__RootRenderer_22 == (null as any))) { (this.__RootRenderer_22 = import31._createConditionalRootRenderer(this._DomRootRenderer_21,this.parent.get(import31.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_22;
  }
  get _DomSanitizer_23():import15.DomSanitizerImpl {
    if ((this.__DomSanitizer_23 == (null as any))) { (this.__DomSanitizer_23 = new import15.DomSanitizerImpl()); }
    return this.__DomSanitizer_23;
  }
  get _Sanitizer_24():any {
    if ((this.__Sanitizer_24 == (null as any))) { (this.__Sanitizer_24 = this._DomSanitizer_23); }
    return this.__Sanitizer_24;
  }
  get _ViewUtils_25():import16.ViewUtils {
    if ((this.__ViewUtils_25 == (null as any))) { (this.__ViewUtils_25 = new import16.ViewUtils(this._RootRenderer_22,this._APP_ID_14,this._Sanitizer_24)); }
    return this.__ViewUtils_25;
  }
  get _IterableDiffers_26():any {
    if ((this.__IterableDiffers_26 == (null as any))) { (this.__IterableDiffers_26 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_26;
  }
  get _KeyValueDiffers_27():any {
    if ((this.__KeyValueDiffers_27 == (null as any))) { (this.__KeyValueDiffers_27 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_27;
  }
  get _SharedStylesHost_28():any {
    if ((this.__SharedStylesHost_28 == (null as any))) { (this.__SharedStylesHost_28 = this._DomSharedStylesHost_19); }
    return this.__SharedStylesHost_28;
  }
  get _Title_29():import17.Title {
    if ((this.__Title_29 == (null as any))) { (this.__Title_29 = new import17.Title()); }
    return this.__Title_29;
  }
  get _ROUTER_CONFIGURATION_30():any {
    if ((this.__ROUTER_CONFIGURATION_30 == (null as any))) { (this.__ROUTER_CONFIGURATION_30 = {}); }
    return this.__ROUTER_CONFIGURATION_30;
  }
  get _LocationStrategy_31():any {
    if ((this.__LocationStrategy_31 == (null as any))) { (this.__LocationStrategy_31 = import5.provideLocationStrategy(this.parent.get(import32.PlatformLocation),this.parent.get(import33.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_30)); }
    return this.__LocationStrategy_31;
  }
  get _Location_32():import18.Location {
    if ((this.__Location_32 == (null as any))) { (this.__Location_32 = new import18.Location(this._LocationStrategy_31)); }
    return this.__Location_32;
  }
  get _UrlSerializer_33():import19.DefaultUrlSerializer {
    if ((this.__UrlSerializer_33 == (null as any))) { (this.__UrlSerializer_33 = new import19.DefaultUrlSerializer()); }
    return this.__UrlSerializer_33;
  }
  get _RouterOutletMap_34():import20.RouterOutletMap {
    if ((this.__RouterOutletMap_34 == (null as any))) { (this.__RouterOutletMap_34 = new import20.RouterOutletMap()); }
    return this.__RouterOutletMap_34;
  }
  get _NgModuleFactoryLoader_35():import21.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_35 == (null as any))) { (this.__NgModuleFactoryLoader_35 = new import21.SystemJsNgModuleLoader(this._Compiler_13,this.parent.get(import21.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_35;
  }
  get _ROUTES_36():any[] {
      if ((this.__ROUTES_36 == (null as any))) { (this.__ROUTES_36 = [[
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'home',
          component: import34.HomeComponent
        }
        ,
        {
          path: 'ca',
          component: import35.CAComponent
        }
        ,
        {
          path: 'inaugration',
          component: import36.InaugrationComponent
        }
        ,
        {
          path: '**',
          component: import34.HomeComponent
        }

      ]
    ]); }
    return this.__ROUTES_36;
  }
  get _Router_37():any {
    if ((this.__Router_37 == (null as any))) { (this.__Router_37 = import5.setupRouter(this._ApplicationRef_12,this._UrlSerializer_33,this._RouterOutletMap_34,this._Location_32,this,this._NgModuleFactoryLoader_35,this._Compiler_13,this._ROUTES_36,this._ROUTER_CONFIGURATION_30)); }
    return this.__Router_37;
  }
  get _ActivatedRoute_38():any {
    if ((this.__ActivatedRoute_38 == (null as any))) { (this.__ActivatedRoute_38 = import5.rootRoute(this._Router_37)); }
    return this.__ActivatedRoute_38;
  }
  get _APP_BOOTSTRAP_LISTENER_39():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_39 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_39 = [import5.initialRouterNavigation(this._Router_37,this._ROUTER_CONFIGURATION_30)]); }
    return this.__APP_BOOTSTRAP_LISTENER_39;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import37.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._AppModule_5 = new import1.AppModule();
    this._ErrorHandler_8 = import4.errorHandler();
    this._ApplicationInitStatus_9 = new import7.ApplicationInitStatus(this.parent.get(import7.APP_INITIALIZER,(null as any)));
    this._Testability_10 = new import8.Testability(this.parent.get(import30.NgZone));
    this._ApplicationRef__11 = new import9.ApplicationRef_(this.parent.get(import30.NgZone),this.parent.get(import38.Console),this,this._ErrorHandler_8,this,this._ApplicationInitStatus_9,this.parent.get(import8.TestabilityRegistry,(null as any)),this._Testability_10);
    return this._AppModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import1.AppModule)) { return this._AppModule_5; }
    if ((token === import39.LOCALE_ID)) { return this._LOCALE_ID_6; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import40.ErrorHandler)) { return this._ErrorHandler_8; }
    if ((token === import7.ApplicationInitStatus)) { return this._ApplicationInitStatus_9; }
    if ((token === import8.Testability)) { return this._Testability_10; }
    if ((token === import9.ApplicationRef_)) { return this._ApplicationRef__11; }
    if ((token === import9.ApplicationRef)) { return this._ApplicationRef_12; }
    if ((token === import10.Compiler)) { return this._Compiler_13; }
    if ((token === import27.APP_ID)) { return this._APP_ID_14; }
    if ((token === import41.DOCUMENT)) { return this._DOCUMENT_15; }
    if ((token === import11.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_16; }
    if ((token === import12.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_17; }
    if ((token === import12.EventManager)) { return this._EventManager_18; }
    if ((token === import13.DomSharedStylesHost)) { return this._DomSharedStylesHost_19; }
    if ((token === import42.AnimationDriver)) { return this._AnimationDriver_20; }
    if ((token === import14.DomRootRenderer)) { return this._DomRootRenderer_21; }
    if ((token === import43.RootRenderer)) { return this._RootRenderer_22; }
    if ((token === import15.DomSanitizer)) { return this._DomSanitizer_23; }
    if ((token === import44.Sanitizer)) { return this._Sanitizer_24; }
    if ((token === import16.ViewUtils)) { return this._ViewUtils_25; }
    if ((token === import45.IterableDiffers)) { return this._IterableDiffers_26; }
    if ((token === import46.KeyValueDiffers)) { return this._KeyValueDiffers_27; }
    if ((token === import13.SharedStylesHost)) { return this._SharedStylesHost_28; }
    if ((token === import17.Title)) { return this._Title_29; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_30; }
    if ((token === import33.LocationStrategy)) { return this._LocationStrategy_31; }
    if ((token === import18.Location)) { return this._Location_32; }
    if ((token === import19.UrlSerializer)) { return this._UrlSerializer_33; }
    if ((token === import20.RouterOutletMap)) { return this._RouterOutletMap_34; }
    if ((token === import47.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_35; }
    if ((token === import48.ROUTES)) { return this._ROUTES_36; }
    if ((token === import37.Router)) { return this._Router_37; }
    if ((token === import49.ActivatedRoute)) { return this._ActivatedRoute_38; }
    if ((token === import27.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_39; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__11.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);